name = "coursegen-workers"
main = "src/worker.ts"
compatibility_date = "2023-06-04"

# PRODUCTION
[env.production]
name = "coursegen-worker-prod"
routes = [{ pattern = "api.crsegen.com", custom_domain = true, zone_name = "crsegen.com" }]
workers_dev = false

[env.production.vars]
ENVIRONMENT = "PRODUCTION"

[[env.production.queues.producers]]
queue = "lesson-content-create-queue-prod"
binding = "LESSON_CONTENT_CREATE_QUEUE"

[[env.production.queues.consumers]]
queue = "lesson-content-create-queue-prod"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 0
max_concurrency = 10
dead_letter_queue = "lesson-content-create-queue-dlq-prod"

# STAGING
[env.staging]
name = "coursegen-worker-staging"
routes = [{ pattern = "staging_api.crsegen.com", custom_domain = true, zone_name = "crsegen.com" }]
workers_dev = true

[env.staging.vars]
ENVIRONMENT = "STAGING"

[[env.staging.queues.producers]]
queue = "lesson-content-create-queue-staging"
binding = "LESSON_CONTENT_CREATE_QUEUE"

[[env.staging.queues.consumers]]
queue = "lesson-content-create-queue-staging"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 0
max_concurrency = 1
dead_letter_queue = "lesson-content-create-queue-dlq-staging"


# LOCAL
[env.local.vars]
ENVIRONMENT = "DEVELOPMENT"

[[env.local.queues.producers]]
queue = "lesson-content-create-queue"
binding = "LESSON_CONTENT_CREATE_QUEUE"

[[env.local.queues.consumers]]
queue = "lesson-content-create-queue"
max_batch_size = 1
max_batch_timeout = 30
max_retries = 0
max_concurrency = 1
dead_letter_queue = "lesson-content-create-queue-dlq"

# [env.staging]
# MY_VARIABLE = "staging_value"

# [env.shared]
# SHARED_VARIABLE = "shared_value"
