name: PRODUCTION - Deploy Migrations and Workers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-migrations:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PROD_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}
      OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
      OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
      ENV_NAME: production

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.27.10

      - run: |
          supabase link --project-ref ${{ secrets.PROD_PROJECT_ID }}
          supabase db push

  deploy-workers:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Cache npm packages
        uses: actions/cache@v2.1.7
        with:
          path: |
            ./workers/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('./workers/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install --prefix ./workers
      - name: Publish to production
        uses: cloudflare/wrangler-action@2.0.0
        with:
          command: publish --env production
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: 'production'
          workingDirectory: 'workers'
          secrets: |
            SUPABASE_URL
            SUPABASE_SERVICE_ROLE_KEY
            OPENAI_API_KEY
            OPENAI_ORG
            HELICONE_API_KEY
            STRIPE_API_KEY
            STRIPE_WEBHOOK_SECRET
        env:
          SUPABASE_URL: ${{ secrets.PROD_SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.PROD_SUPABASE_SERVICE_ROLE_KEY }}
          OPENAI_API_KEY: ${{ secrets.PROD_OPENAI_API_KEY }}
          OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
          HELICONE_API_KEY: ${{ secrets.PROD_HELICONE_API_KEY }}
          STRIPE_API_KEY: ${{ secrets.PROD_STRIPE_API_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.PROD_STRIPE_WEBHOOK_SECRET }}
          