name: Deploy Migrations to Test (for local testing)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      PROJECT_ID: ${{ secrets.TEST_PROJECT_ID }}
      OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
      OPENAI_ORG: ${{ secrets.OPENAI_ORG }}
      UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.27.10

      - run: |
          supabase link --project-ref $PROJECT_ID
          supabase db push
          supabase functions deploy new_course --project-ref ${{ secrets.TEST_PROJECT_ID }} --import-map "./supabase/functions/import_map.json"
          supabase functions deploy new_course_v2 --project-ref ${{ secrets.TEST_PROJECT_ID }} --import-map "./supabase/functions/import_map.json"
          supabase functions deploy lesson_content --project-ref ${{ secrets.TEST_PROJECT_ID }} --import-map "./supabase/functions/import_map.json"
          supabase functions deploy lesson_content_v2 --project-ref ${{ secrets.TEST_PROJECT_ID }} --import-map "./supabase/functions/import_map.json"
          supabase functions deploy get_course --project-ref ${{ secrets.TEST_PROJECT_ID }} --import-map "./supabase/functions/import_map.json"
          supabase functions deploy save_course --project-ref ${{ secrets.TEST_PROJECT_ID }} --import-map "./supabase/functions/import_map.json"